#
#
#                <--- TicketSystem --->
#          Created by Twan Luttik, Config version 1.0
#
update_message: true
host: 'localhost'
port: 3306
database: 'tutorial'
username: 'root'
password: 'password'
table: 'player_data'